[build]
  command = "npm ci --prefix MCP && npm run build --prefix MCP"
  publish = "MCP/out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200